### ISSUE TITLE
Items not deleted

### ISSUE THREAD

**Issue by melefabrizio** [markomarkovic/simple-php-git-deploy#66]
Everything works fine, just when I delete a directory or a file in the local repo and push the commit on the remote server nothing is changed, I can see from 'top' git and rsync are called and executed just like when I edit or add a file/directory

**Comment by markomarkovic** [comment]
If you call the deploy script directly from the browser, you can see the output of all the commands. Perhaps it's a permissions issue? Anyway, check the output.

**Comment by bbarnwell** [comment]
I have a similar question. In the config, we have DELETE_FILES set to false so that files on the server that are not in the repo remain on the server. However, we have some files we have deleted from the repo that we would like removed from the server (in this case, removal of an unused WP plugin). What is the best way to do this, without deleting all non-repo files from the server (i.e. uploades, etc)?

**Comment by markomarkovic** [comment]
Either delete the files manually, or use `DELETE_FILES` in combination with  `EXCLUDE` where you specify all the files/patterns that are not to be deleted.

**Comment by bbarnwell** [comment]
Perfect - thank you!
